services:
  - type: web
    name: gremuiv-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python render_start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /
    autoDeploy: true

